### PR TITLE
WIP: Add SimpleSAML installation task to Ansible playbook

### PR DESCRIPTION
**Pull request by krishmoodbidri**
This commit adds a new task to the Ansible playbook to download and install SimpleSAML

### CODE REVIEW

**Comment by krishmoodbidri** [comment]
Playbook for the installation and configuration of SimpleSAMLphp, which is needed for the implementation of SSO on Xdmod. The playbook installs all necessary prerequisites such as PHP and required PHP modules, downloads the SimpleSAMLphp package, extracts it, renames the directory, and creates necessary directories for configuration, metadata and certificates.

Additionally, the playbook copies the configuration files config.php, authsources.php, and saml20-idp-remote.php and certificates saml.pem and saml.crt to the relevant directories. The Apache configuration file is also modified to include the necessary settings for SimpleSAMLphp and the Apache service is restarted.

**Comment by eesaanatluri** [comment]
@krishmoodbidri could you please send in a PR with the branch name changed to something like `feat-add-sso` since this is a feature branch

**Comment by eesaanatluri** [comment]
@krishmoodbidri This role needs to be added to the playbook `clustermon.yml` otherwise, it can't run.

**Comment by eesaanatluri** [comment]
Okay, I'll answer my own question.

This error is seen because ansible is using python2.x for its interpreter and it seems that it doesn't find a CA certificate on host (though it is available) by default, that would allow you to verify the certificate that the server presents to you.
However, if we point the interpreter to use python3 this issue is resolved.

**Comment by krishmoodbidri** [comment]
> @krishmoodbidri This role needs to be added to the playbook `clustermon.yml` otherwise, it can't run.

**Comment by eesaanatluri** [comment]
After pointing the ansible python interpreter to use py3 I see this error
```
TASK [simplesaml : Download SimpleSAMLphp] **********************************************************
fatal: [ohpc]: FAILED! => {"changed": false, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
```

**Comment by eesaanatluri** [comment]
It looks like the selinux is causing issues but setting selinux from enforcing -> permissive didn't solve the error we are seeing. It looked like the python binding `libselinux-python` is missing.

`sudo yum -y install libselinux-python3` solved this issue but again we need to make a decision whether to install it system-wide or just in the venv (if it makes sense there)

**Comment by eesaanatluri** [comment]
I see the following error,
```
TASK [simplesaml : Extract SimpleSAMLphp] ***********************************************************
fatal: [ohpc]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/simplesamlphp.tar.gz\". Make sure the required command to extract the file is installed. Command \"/usr/bin/unzip\" could not handle archive. Command \"/usr/bin/gtar\" could not handle archive."}
```

Pretty sure it is not a valid tar file.

I can confirm it is not a valid tar file. It is an html page. 
```
[centos@ohpc CRI_Cluster_Monitor]$ file /tmp/simplesamlphp.tar.gz
/tmp/simplesamlphp.tar.gz: HTML document, UTF-8 Unicode text
``` 

The URL you used to download simplesaml is wrong @krishmoodbidri 
Here is the correct one.
https://github.com/simplesamlphp/simplesamlphp/releases/download/v1.19.7/simplesamlphp-1.19.7.tar.gz

This will download the actual .tar.gz file that can be extracted.

**Comment by krishmoodbidri** [comment]
changes suggested
1. renaming the branch: Here's my suggestion, I'll continue work on this branch, then when its ready, I'll create another branch and put in a PR with a squashed commits
2. I uploaded the task to clustermon.yml
3. Created a venv to with python3 and installing these packages to the venv

**Pull request closed without merging**
